services:
  - type: web
    name: guess-x
    runtime: docker
    plan: free
    region: singapore
    envVars:
      - key: APP_NAME
        value: Guess-X
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        fromService:
          type: web
          name: guess-x
          property: host
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: guess-x-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: guess-x-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: guess-x-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: guess-x-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: guess-x-db
          property: password
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database

databases:
  - name: guess-x-db
    plan: free
    region: singapore
    databaseName: guessx
    user: guessx
